#-------------------------------
# Site Settings
title: AI4NA 
# logo: 'https://static-00.iconduck.com/assets.00/dna-emoji-2048x2026-zhdjmaa2.png'  # Top left corner logo
description: AI4NA Workshop @ ICLR'25
color_scheme: auto  # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
      submenu:
      # - url: '/contact/'
      #   title: 'Contact'
      # - url: '/elements/'
      #   title: 'Organizing Committee'
      # - url: '/elements/'
      #   title: 'Program Committee'
    - title: 'Call for Papers'
      url: '/submissions/'
    # - title: 'Reviewers Guidelines'
    #   url: '/reviewers/' 
    - title: 'Organizers'
      url: '/organizers/'
    - title: 'Schedule'
      url: '/agenda/'
    - title: 'Accepted Papers'
      url: '/accepted/'
    # - title: 'Submissions'
    #   url: '/submissions/'
  #  - title: 'Prizes'
  #    url: '/prizes/'
    # - title: 'Speakers'
    #   url: '/work/'
    # - title: 'Breakout Notes'
    #   url: '/breakout/'



#      submenu:
#      - url: '/contact/'
#        title: 'Steering Committee'
#      - url: '/elements/'
#        title: 'Organizing Committee'
#      - url: '/elements/'
#        title: 'Program Committee'


#-------------------------------
# Author Settings
author:
  author__name: AI4NA
  author__bio: This workshop aims to spotlight nucleic acids as the next frontier for AI research. By bringing together experts from machine learning and biology, we will explore how AI can address key challenges in nucleic acids research, such as RNA tertiary structure prediction, understanding nucleic acid interactions, and designing bespoke RNA/DNA molecules with therapeutic potential.
  author__avatar: images/other/dna.svg

social:
#- {icon: "ion-logo-twitter", link: "https://twitter.com"}
#- {icon: "ion-logo-facebook", link: "https://facebook.com"}
#- {icon: "ion-logo-instagram", link: "https://instagram.com"}
#- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
#- {icon: "ion-logo-github", link: "https://github.com"}
#- {icon: "ion-logo-vimeo", link: "https://vimeo.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: AI4NA Workshop 
  hero__workshopname: 'Artificial Intelligence for Nucleic Acids'
  hero__subtitle: ICLR'25 - Apr (TBC)th, Singapore
  hero__description: This workshop aims to spotlight nucleic acids as the next frontier for AI research. By bringing together experts from machine learning and biology, we will explore how AI can address key challenges in nucleic acids research, such as RNA tertiary structure prediction, understanding nucleic acid interactions, and designing bespoke RNA/DNA molecules with therapeutic potential.
  hero__image: images/other/singapore-merlion.jpg
  # hero__image: https://upload.wikimedia.org/wikipedia/commons/f/f1/Singapore_Merlion.jpg
  # hero__image: "https://wallpaper.forfun.com/fetch/b4/b477aa17c628ebc4cf68cbdc091e9b0d.jpeg"


#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: Sponsors
  logos__description: Thank you to our sponsors!

logo__items:
  - name: Nvidia
    link: https://www.nvidia.com/
    image: /images/sponsors/Nvidia_logo.jpeg

  - name: ONT
    link: https://nanoporetech.com/
    image: /images/sponsors/ONT.png

  - name: Inceptive
    link: https://inceptive.life/
    image: /images/sponsors/Inceptive.svg

  - name: Oraclum Capital
    link: https://oraclumcapital.com/
    image: /images/sponsors/Orca.svg


  # - name: TBC
  #   link: https://thumbs.dreamstime.com/b/to-be-announced-red-rubber-stamp-over-white-background-86701643.jpg
  #   image: https://thumbs.dreamstime.com/b/to-be-announced-red-rubber-stamp-over-white-background-86701643.jpg

  # - name: TBC
  #   link: https://thumbs.dreamstime.com/b/to-be-announced-red-rubber-stamp-over-white-background-86701643.jpg
  #   image: https://thumbs.dreamstime.com/b/to-be-announced-red-rubber-stamp-over-white-background-86701643.jpg

#-------------------------------
# Newsletter
mailchimp:
  enable: true
  mailchimp__identifier: https://bio.us22.list-manage.com/subscribe/post?u=c11b5cdfac933324ba6b81e53&amp;id=b2be655647&amp;f_id=0045cbe1f0 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__input__text: Your email address...
  mailchimp__button__text: Register Interest


#-------------------------------
# Work Settings
work:
  enable: true
  work__title: Speakers and Panelists
  # work__description: Leading researchers from Industry and Academia will be at the workshop (listed alphabetically by the last name).

#-------------------------------
# Speakers Settings
speakers:
  enable: true
  speakers__title: Speakers
  # speakers__description: Leading researchers from Industry and Academia will be at the workshop (listed alphabetically by the last name).

#-------------------------------
# Panelists Settings
panelists:
  enable: true
  panelists__title: Panelists
  # panelists__description: Leading researchers from Industry and Academia will be at the workshop (listed alphabetically by the last name).


#-------------------------------
# Testimonials Section
testimonials:
  enable: true

testimonial__title: Senior Organizers
testimonial__description: Rally the community, establish and maintain event credibility by endorsing the workshop and setting the scope and vision as senior advisors.

testimonial__items:
  - name: Bruno Trentini
    image: /images/organizers/Bruno_Trentini_2.jpeg
    designation: "NVIDIA,\nUniversity of Oxford"    
    link: "https://www.linkedin.com/in/btrentini"
    content: content

  - name: Max Ward
    image: /images/organizers/Max_Ward.webp
    designation: The University of Western Australia
    link: "https://research-repository.uwa.edu.au/en/persons/max-ward"
    content: content

  - name: Maria Brbić
    image: /images/organizers/Maria_Brbic.jpg
    designation: EPFL
    link: "https://people.epfl.ch/maria.brbic"
    content: Maria is an Assistant Professor of Computer Science and Life Sciences at EPFL, affiliated with the EPFL Institute of Bioengineering. Her research focuses on machine learning for biomedical research. She co-organized the ICLR’24 Workshop on Machine Learning for Genomics Explorations, ICML’23 Workshop on Computational Biology, and NeurIPS ‘23 Workshop on AI for Science. Maria will mainly handle the Overleaf/Doc template, submission guidelines, and speaker relations.

  - name: Bryan Hooi
    image: /images/organizers/Bryan_Hooi.jpg
    designation: National University of Singapore
    link: "https://bhooi.github.io/"
    content: content

  - name: Fran Supek
    image: /images/organizers/Fran_Supek.jpeg
    designation: University of Copenhagen
    link: "https://www.linkedin.com/in/fran-supek-genome-data-science"
    content: content

  - name: Pietro Liò
    image: /images/organizers/Pietro_Lio.jpeg
    designation: University of Cambridge
    link: "https://www.cl.cam.ac.uk/~pl219/"
    content: content

  - name: Elena Rivas
    image: /images/organizers/Elena_Rivas_2.jpeg
    designation: Harvard University
    link: "https://www.mcb.harvard.edu/directory/elena-rivas/"
    content: content

  - name: Mile Šikić
    image: /images/organizers/Mile_Sikic_2.png
    designation: "Genome Institute of Singapore (A*STAR)\nFER, University of Zagreb"
    link: "https://www.a-star.edu.sg/gis/our-people/faculty-staff/members/mile-sikic"
    content: content


# Ogranizers Section
organizers:
  enable: true

organizers__title: Junior Organizers
organizers__description: Dedicated to community outreach, workshop logistics, and managing submissions & reviews.

organizers__items:
  - name: Ivona Martinović
    image: /images/organizers/Ivona_Martinovic.jpeg
    designation: "Genome Institute of Singapore (A*STAR)\nNational University of Singapore"
    link: "https://www.linkedin.com/in/ivona-martinovic"
    content: content

  - name: Lovro Vrček
    image: /images/organizers/Lovro_Vrcek_2.png
    designation: "Genome Institute of Singapore (A*STAR)\nFER, University of Zagreb"
    link: "https://www.linkedin.com/in/lovro-vrcek/"
    content: content

  - name: Chaitanya Joshi
    image: /images/organizers/Chaitanya_Joshi.jpeg
    designation: University of Cambridge
    link: "https://www.chaitjo.com/"
    content: content

  - name: Tin Vlašić
    image: /images/organizers/Tin_Vlasic.jpg
    designation: Genome Institute of Singapore (A*STAR)
    link: "https://sites.google.com/view/tinvlasic"
    content: content

  - name: Agata M. Kilar
    image: /images/organizers/Agata_Kilar.jpg
    designation: Harvard University
    link: "https://www.linkedin.com/in/agata-kilar/"
    content: content


#-------------------------------
# Program Committee Section
programs:
  enable: true

programs__title: Program Committee
programs__description: Serving as reviewers and area chairs


#-------------------------------
# Thanks Section
thanks:
  enable: true

thanks__title: Special Thanks
thanks__description: To our Area Chairs


#-------------------------------
# Thanks Section
accepted:
  enable: true

accepted__title: Accepter Papers
accepted__description: Accepted Papers


#-------------------------------
# Blog Section
blog:
  enable: true

blog__settings:
  blog__title: Agenda
  blog__description: To be added here




#-------------------------------
# Footer Settings
footer__background__image: /images/other/singapore-skyline.jpg

#-------------------------------
# Contact Settings
contact:
  email: ai4na.workshop@gmail.com  # workshop@ml4lms.bio # Add your form_id
  form_id: "https://formspree.io/f/movqoapb"
  description: If you have any questions, please do reach out to the organizers # Add a description of your form
  title: Contact Us


# NOTE
# Akio theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id